filmstriben/mobilesearch_rest

- src/AppBundle/Repositories/ListsRepository.php
- src/AppBundle/Tests/ListsFetchTest.php
https://inlead.atlassian.net/browse/FIL-1004
> FIL-1004 - Use distinct node id's when filtering list items.

- README.md
- composer.json
- src/AppBundle/Controller/RestController.php
- src/AppBundle/DataFixtures/MongoDB/ConfigurationFixtures.php
- src/AppBundle/Document/Agency.php
- src/AppBundle/Document/Configuration.php
- src/AppBundle/IO/ConfigurationOutput.php
- src/AppBundle/Resources/fixtures/agencies.yml
- src/AppBundle/Resources/fixtures/configuration.yml
- src/AppBundle/Rest/RestBaseRequest.php
- src/AppBundle/Rest/RestConfigurationRequest.php
- src/AppBundle/Tests/AbstractBaseTest.php
- src/AppBundle/Tests/ConfigurationTest.php
https://inlead.atlassian.net/browse/FIL-1078
> FIL-1078 - Exposed configurations.

- app/config/config_dev.yml
- app/config/services.yml
- src/AppBundle/EventListener/ContentRemoveListener.php
- src/AppBundle/Repositories/ListsRepository.php
https://inlead.atlassian.net/browse/FIL-1072
> FIL-1072 - Cleanup lists on content removal.

- src/AppBundle/Repositories/ListsRepository.php
https://inlead.atlassian.net/browse/FIL-1072
> FIL-1072 - Optional agency filter.

- src/AppBundle/Controller/ImageController.php
https://inlead.atlassian.net/browse/FIL-1104
> FIL-1104 - Correct quality settings and image sharpness kernel.

- src/AppBundle/Controller/ImageController.php
https://inlead.atlassian.net/browse/FIL-1108
> FIL-1108 - Imagick support and exposed settings.

- composer.json
- composer.lock
- src/AppBundle/Controller/ImageController.php
> FIL-1114 - Extend image route with convertion options.

- composer.json
> FIL-1114 - Skip mongo extension version check.

- src/AppBundle/Controller/ImageController.php
> FIL-1114 - Typo's.

- composer.json
- composer.lock
- src/AppBundle/Controller/RestController.php
- src/AppBundle/Document/Content.php
- src/AppBundle/Rest/RestContentRequest.php
https://inlead.atlassian.net/browse/FIL-1116
> FIL-1116 - Extended search.

- src/AppBundle/Controller/RestController.php
https://inlead.atlassian.net/browse/FIL-1116
> FIL-1116 - Regex fix.

- composer.json
- composer.lock
- src/AppBundle/Controller/ImageController.php
> FIL-1114 - Mime detection fix.

- src/AppBundle/Document/Content.php
https://inlead.atlassian.net/browse/FIL-1125
> FIL-1125 - Accept named lists.

- src/AppBundle/Controller/ImageController.php
> FIL-1114 - Serve jpeg's by default.

- src/AppBundle/Controller/ImageController.php
> FIL-1114 - Change to ImageController.

- src/AppBundle/Controller/ImageController.php
https://inlead.atlassian.net/browse/FIL-1144
> FIL-1144 - Sharpen by default.

- src/AppBundle/Controller/RestController.php
- src/AppBundle/Document/Lists.php
- src/AppBundle/Rest/RestListsRequest.php
https://inlead.atlassian.net/browse/FIL-1173
> FIL-1173 - Listen for list agency.

- src/AppBundle/Controller/RestController.php
https://inlead.atlassian.net/browse/FIL-1200
> FIL-1200 - Sorting parameter.

- src/AppBundle/Controller/RestController.php
This commit allows using `in` in search-extended route, so one would not need to write lots of `OR`'s for same field, but just one IN and a delimited list of values: `("nid[eq]:1000" OR "nid[eq]:1001" OR "nid[eq]:1002") vs ("nid[in]:1000|1001|1002")`.
> FIL-NO_TASK - Stub for 'in' operator.

- src/AppBundle/Controller/RestController.php
- src/AppBundle/DataFixtures/MongoDB/ListsFixtures.php
- src/AppBundle/IO/ListItem.php
- src/AppBundle/Resources/fixtures/lists.yml
- src/AppBundle/Resources/fixtures/os.yml
- src/AppBundle/Tests/ContentFetchTest.php
- src/AppBundle/Tests/ContentSearchExtendedTest.php
- src/AppBundle/Tests/ContentSearchTest.php
- src/AppBundle/Tests/ListsFetchTest.php
https://inlead.atlassian.net/browse/FIL-1267
> FIL-1267 - Fix for and/or in query. 

- src/AppBundle/Ast/AbstractNode.php
- src/AppBundle/Ast/Node.php
- src/AppBundle/Ast/NodeInterface.php
- src/AppBundle/Ast/TransformableNodeInterface.php
- src/AppBundle/Ast/Walker/MongoTreeWalker.php
- src/AppBundle/Ast/Walker/TreeWalkerInterface.php
- src/AppBundle/Controller/RestController.php
- src/AppBundle/Query/Clause.php
- src/AppBundle/Query/ClauseInterface.php
- src/AppBundle/Resources/config/services.yml
- src/AppBundle/Services/SearchQueryLexer.php
- src/AppBundle/Services/SearchQueryParser.php
https://inlead.atlassian.net/browse/FIL-1279
> FIL-1279 - Lexing and parsing of the query.

- src/AppBundle/Ast/Walker/MongoTreeWalker.php
https://inlead.atlassian.net/browse/FIL-1279
> FIL-1279 - Fixes nid field type casting.

- src/AppBundle/Controller/RestController.php
- src/AppBundle/Rest/RestContentRequest.php
https://inlead.atlassian.net/browse/FIL-1287
> FIL-1287 - External flag filter.

- src/AppBundle/Rest/RestContentRequest.php
https://inlead.atlassian.net/browse/FIL-1287
> FIL-1287 - Typo.

- src/AppBundle/Controller/RestController.php
https://inlead.atlassian.net/browse/FIL-1287
> FIL-1287 - Default external flag set as 0.

- src/Document/Lists.php
https://inlead.atlassian.net/browse/FIL-1291
> FIL-1291 - Store list criteria as json string.

- src/Controller/ImageController.php
https://inlead.atlassian.net/browse/FIL-1293
> FIL-1293 - Minimal quality fix.

- README.md
- src/Controller/RestController.php
https://inlead.atlassian.net/browse/FIL-1293
> FIL-1293 - CRUD routes documentation.

- src/Ast/Walker/MongoTreeWalker.php
https://inlead.atlassian.net/browse/FIL-1301
> FIL-1301 - Fix for IN operator.

- config/packages/nelmio_api_doc.yaml
- phpunit.xml.dist
- src/Services/SearchQueryLexer.php
- src/Tests/ContentSearchExtendedTest.php
https://inlead.atlassian.net/browse/FIL-1353
> FIL-1353 - Allow dashes in extended search query.

- src/Controller/RestController.php
- src/DataFixtures/MongoDB/MenuFixtures.php
- src/Document/Menu.php
- src/Rest/RestMenuRequest.php
- src/Services/MatchOrderer.php
- src/Tests/MenuFetchTest.php
https://inlead.atlassian.net/browse/FIL-1443
> FIL-1443 - Feature: CRUD operations for top menu links and render as image option.

- .gitignore
- src/Controller/RestController.php
- src/Document/Menu.php
- src/Rest/RestMenuRequest.php
https://inlead.atlassian.net/browse/FIL-1443
> FIL-1443 - Feature: Support for menu background image.

- src/Document/Menu.php
https://inlead.atlassian.net/browse/FIL-1443
> FIL-1443 - Fix: Enforce data type.

- src/Document/Menu.php
https://inlead.atlassian.net/browse/FIL-1443
> FIL-1443 - Fix: Enforce menu items data type.
